Lesson 3
DzenAsad/tms2021Android pull request #5
Opened 2021-01-26 13:26 UTC by DzenAsad

Watch me pls)

2021-01-26 14:00 UTC, GlebLitvinov requested changes

2021-01-26 14:00 UTC, GlebLitvinov commented on Lesson3/src/Homework.java
> +    public static int operation(int number) {
good

2021-01-26 14:00 UTC, GlebLitvinov commented on Lesson3/src/Homework.java
> +    public static void foobar(int number) {
nice!

2021-01-26 14:00 UTC, GlebLitvinov commented on Lesson3/src/Homework.java
> +                array[i][j] = symbol(random.nextInt(100));
great. You can change type of array and return type of method "symbol" to char, though, since there is only 1 symbol to store

2021-01-26 14:00 UTC, GlebLitvinov commented on Lesson3/src/Homework.java
> +    public static String symbol(int number) {
if number will be equal to 21 this method will return "-", but according to the task it should return "+"

2021-01-26 14:57 UTC, DzenAsad commented on Lesson3/src/Homework.java
> +                array[i][j] = symbol(random.nextInt(100));
set to char

2021-01-26 14:57 UTC, DzenAsad commented on Lesson3/src/Homework.java
> +    public static String symbol(int number) {
fix

2021-01-27 13:54 UTC, GlebLitvinov approved these changes

2021-01-27 16:01 UTC, merged